[package]
name = "quecto_gpt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmap2 = "0.5.10"
nalgebra = "0.32.2"
ndarray = "0.15.6"
safetensors = "0.3.1"
serde_json = "1.0.96"
